-- MySQL Script generated by MySQL Workbench
-- Thu Nov 20 09:15:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`racas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`racas` (
  `id_racas` INT NOT NULL AUTO_INCREMENT,
  `nome_raca` VARCHAR(100) NOT NULL,
  `porte_raca` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_racas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`animais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`animais` (
  `id_animais` INT NOT NULL AUTO_INCREMENT,
  `nome_animais` VARCHAR(100) NOT NULL,
  `idade_animais` INT NULL,
  `status` VARCHAR(20) NULL,
  `racas_id_racas` INT NOT NULL,
  PRIMARY KEY (`id_animais`),
  INDEX `fk_animais_racas_idx` (`racas_id_racas` ASC) VISIBLE,
  CONSTRAINT `fk_animais_racas`
    FOREIGN KEY (`racas_id_racas`)
    REFERENCES `mydb`.`racas` (`id_racas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
